#!/usr/bin/env python3

import json
import yaml
import copy


def update_item(item, language):
    new_item = copy.deepcopy(item)
    new_item["title"] = new_item["title"][language]
    if "children" in new_item:
        new_item["children"] = update_titles(new_item["children"], language)
    return new_item

def update_titles(contents, language):
    return [update_item(x, language) for x in contents if language in x["title"]]

contents = yaml.safe_load(open("directory.yaml"))

contents_en = update_titles(contents, "en")
contents_zh = update_titles(contents, "zh")

contents = {"en": contents_en, "zh": contents_zh}

json.dump(contents, open("docs/directory.json", "w"), ensure_ascii=False)
