name: Check Markdown links

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
       folder-path: './docs'
