name: ci

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  quick-start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: pull images
        run: docker-compose -f assets/quick-start.yaml pull

      - name: set env
        run: |
          image=$(cat assets/quick-start.yaml | grep "image:.*hstreamdb/hstream" | head -n 1 | awk '{print $2}')
          echo "IMAGE=$image" >> $GITHUB_ENV

      - name: quick start a hstream cluster
        run: |
          docker-compose -f assets/quick-start.yaml up -d
          docker-compose -f assets/quick-start.yaml run --no-deps --rm hserver0 \
            bash -c 'set -e; \
              export timeout=120; \
              until ( \
                /usr/local/bin/hadmin server --host hserver0 --port 6570 status && \
                /usr/local/bin/hadmin server --host hserver1 --port 6572 status \
              ); do \
                >&2 echo "Waiting for cluster..."; \
                sleep 10; \
                timeout=$((timeout - 10)); \
                [ $timeout -le 0 ] && echo "Timeout!" && exit 1; \
              done; \
              exit 0 \
            '

      - name: test simple sql
        run: |
          echo "Docker image: ${{ env.IMAGE }}"
          STREAM=$(\
            docker run -t --rm --name some-hstream-cli --network host \
              ${{ env.IMAGE }} hstream --port 6570 sql -e "CREATE STREAM demo;" \
            | tr -d '[:space:]')
          [ "$STREAM" != "demo" ] && echo "$STREAM" && exit 1;

          docker run -td --rm --name some-hstream-cli --network host \
            ${{ env.IMAGE }} hstream --port 6570 sql -e \
            "SELECT * FROM demo WHERE humidity > 70 EMIT CHANGES;"
          sleep 5
          docker exec -t some-hstream-cli hstream --port 6570 sql -e "INSERT INTO demo (temperature, humidity) VALUES (22, 80);"
          docker exec -t some-hstream-cli hstream --port 6570 sql -e "INSERT INTO demo (temperature, humidity) VALUES (15, 20);"
          docker exec -t some-hstream-cli hstream --port 6570 sql -e "INSERT INTO demo (temperature, humidity) VALUES (31, 76);"
          docker exec -t some-hstream-cli hstream --port 6570 sql -e "INSERT INTO demo (temperature, humidity) VALUES ( 5, 45);"
          docker exec -t some-hstream-cli hstream --port 6570 sql -e "INSERT INTO demo (temperature, humidity) VALUES (27, 82);"
          docker exec -t some-hstream-cli hstream --port 6570 sql -e "INSERT INTO demo (temperature, humidity) VALUES (28, 86);"
          sleep 5
          OUTPUT=$(mktemp)
          docker logs some-hstream-cli > $OUTPUT
          cat $OUTPUT
          cmp --silent $OUTPUT tests/quick_start_sql_001.txt || exit 1
