name: ci

on:
  push:
    branches: [main, release]

  pull_request:
    branches: [main, release]

jobs:
  quick-start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: pull images
        run: docker-compose -f assets/quick-start.yaml pull

      - name: quick start a hstream cluster
        run: ./tests/start_cluster.sh

      - name: test simple sql
        run: ./tests/test_quick_start.sh

  hstreamdb-java-examples:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/hstreamdb-java-examples
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew spotlessJavaCheck

      - run: docker compose -f ../../assets/quick-start.yaml up -d

      - run: sleep 30

      - run: ./gradlew run
