name: ci

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  quick-start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: pull images
        run: docker-compose -f assets/quick-start.yaml pull

      - name: quick start a hstream cluster
        run: ./tests/start_cluster.sh

      - name: test simple sql
        run: ./tests/test_quick_start.sh
