name: Tag docs

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy
        run: |
          git config user.name "GithubAction"
          git config user.email "z@hstream.io"

          TAG=${GITHUB_REF#refs/*/}
          mike deploy --push --rebase --force ${TAG}
          mike set-default --push latest
